/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package village;

public class App {
    public static void main(String[] args) {
        System.out.println("For this tutorial, the story is in the tests. Perhaps you wanted to 'gradle test' rather than 'gradle run'?");
    }
}
